apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-service.fullname" . }}-secret
  labels:
    {{- include "go-service.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secret.apiKey | default "Y2hhbmdlbWU=" | quote }}
