---
- name: Create alertmanager user
  ansible.builtin.user:
    name: alertmanager
    shell: /bin/false
    system: true
    create_home: false

- name: Create alertmanager directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: "0755"
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: Download Alertmanager
  ansible.builtin.get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz
    mode: "0644"

- name: Extract Alertmanager
  ansible.builtin.unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp
    remote_src: true

- name: Move alertmanager binaries
  ansible.builtin.copy:
    src: "/tmp/alertmanager-0.27.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    owner: alertmanager
    group: alertmanager
    remote_src: true
  loop:
    - alertmanager
    - amtool

- name: Deploy alertmanager config from template
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: "0644"
  notify: restart alertmanager

- name: Create alertmanager systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/alertmanager.service
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      User=alertmanager
      ExecStart=/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/var/lib/alertmanager
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Start and enable alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: started
    enabled: true
    daemon_reload: true
